### ISSUE TITLE
Is it possible to get a code example?

### ISSUE THREAD

**Issue by Jules-A** [garamond13/kaiser-garamond-window#1]
I've been trying it as a modification to altScale
with:
```
#define bessel_I0(x) ((x) < 4.9706658 ? 1.0 + (x) * (x) / 4.0 + (x) * (x) * (x) * (x) / 64.0 + (x) * (x) * (x) * (x) * (x) * (x) / 2304.0 + (x) * (x) * (x) * (x) * (x) * (x) * (x) * (x) / 147456.0 : inversesqrt(2.0 * M_PI * (x)) * exp(x))
```

```
#elif K == KAISERGARAMOND
    #define k(x) (x <= R ? bessel_I0(P2 * sqrt(1.0 - pow(abs(x) / R, P1))) / bessel_I0(P2) : 0.0)
```

with the parameters you listed but I wasn't able to get desirable results for chroma scaling, is that normal or did I do something wrong? The bessel_IO was taken from your w-image-viewer code.

**Comment by garamond13** [comment]
Kaiser-Garamond is a window and as such shouldn't be used directly. You could, but don't expect good results. For an example it should be used for windowing Sinc, Jinc or Sphinx.

In this code example (modified altUpscaleChroma.glsl) `P1` is beta parameter and `P2` is n parameter.  I didn't implemented some extra checks like is n >= 0 as it should be. Also I did some optimizations like not checking is x <= R, not taking absolute value of x, not normalizing with I0(beta) since all this is done elsewhere in the code.

It is attached as .txt, but feel free to change extension back to original .glsl
[kaisergaramond.txt](https://github.com/garamond13/kaiser-garamond-window/files/13514556/kaisergaramond.txt)

**Comment by Jules-A** [comment]
Oh I see, thanks!
